name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change to your default branch if needed
  pull_request: # Triggers on pull requests
    branches:
      - main # Specify the branches to trigger on pull requests
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set env vars
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
          JWT_SECRET_KEY:  ${{ secrets.JWT_SECRET_KEY }}
        run: |
          # Export secrets as environment variables
          echo "DATABASE_NAME=${DATABASE_NAME}" >> $GITHUB_ENV
          echo "DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> $GITHUB_ENV

    
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '23' # Using OpenJDK 23
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Package with Makefile
        run: make build


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: make docker_build

      - name: Push Docker image
        run: docker push gabjea/weekend-warriors-backend:latest
